1) 두 행렬 A와 B가 주어졌을 때, 행렬 덧셈과 뺄셈을 수행하는 코드를 작성하시오.

In [63]:
import numpy as np

A = np.array([[2, 3], [4, 5]])
B = np.array([[1, 0], [-1, 3]])

# 행렬 덧셈
C_add = A+B #
print("행렬 덧셈:\n", C_add)

# 행렬 뺄셈
C_subtract =A-B
print("행렬 뺄셈:\n", C_subtract)

행렬 덧셈:
 [[3 3]
 [3 8]]
행렬 뺄셈:
 [[1 3]
 [5 2]]


2) 주어진 행렬 A와 스칼라 c에 대해 스칼라 곱을 수행하는 코드를 작성하시오. (밑줄 부분)

In [64]:
import numpy as np

A = np.array([[3, 1], [0, -2]])
c = 4

# 스칼라 곱
C_scalar = np.multiply(A,c)
print("스칼라 곱:\n", C_scalar)



스칼라 곱:
 [[12  4]
 [ 0 -8]]


3) 두 행렬 A와 B의 행렬 곱을 수행하는 코드를 작성하시오. (밑줄 부분).

In [65]:
import numpy as np

A = np.array([[2, 4], [1, 3]])
B = np.array([[1, 2], [0, 1]])

# 행렬 곱셈
C_multiply = np.dot(A,B)
print("행렬 곱셈:\n", C_multiply)

행렬 곱셈:
 [[2 8]
 [1 5]]


4. 주어진 행렬 A의 전치 행렬을 수행하는 코드를 작성하시오. (밑줄 부분). 그리고 결과를 예측하시오.

In [66]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])

# 행렬 전치
A_transpose = A.T.shape
A.shape=(3,2)
A_transpose = A
print("행렬 전치:\n", A_transpose)



행렬 전치:
 [[1 2]
 [3 4]
 [5 6]]


5. 주어진 행렬 A의 역행렬을 수행하는 코드를 작성하시오. (밑줄 부분). 

In [67]:
import numpy as np

A = np.array([[4, 7], [2, 6]])

# 역행렬
A_inverse = np.linalg.inv(A)
print("역행렬:\n", A_inverse)

역행렬:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
