# Ch7 그리기 함수  
- 7-1 OpenCV 좌표계(p134)  
좌표 (100,300)에 원그리기  
-> openCV 캠버스 좌표계처럼 (y,x)형태로 사용하는것도 있다  
이미지의 왼쪽 위가 원점 (0,0)  
오른쪽으로 갈수록 x 값 증가  
아래로 갈수록 y 값 증가

In [4]:
import numpy as np
import cv2 as cv



width = 640
height = 480

img = np.zeros((height, width, 3), np.uint8)

print(img)
img_h = img.shape[0]
img_w = img.shape[1]
img_bpp = img.shape[2]

print(img_h, img_w, img_bpp)

cv.circle(img, (100, 300), 10, (0, 255, 255), -1)

cv.imshow("drawing", img)

cv.waitKey(0)


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
480 640 3


-1

- 7-3 사각형 그리기  
1) 사각형 두좌표(왼쪽 위, 오른쪽 아래)  
  img= cv.rectangle(img,pt1,pt2,color, thickenss)  
  img : 사각형을 그릴 이미지  
  pt1 : 사각형의 왼쪽 위 좌표  
  pt2 : 사각형을 오른쪽 아래 좌표  
  color : 사각형의 색 예) 빨간색(0,0,255)  
  thickenss : 선의 굵기 (-1 일시 내부 채워짐)  

  
   

In [5]:
import numpy as np
import cv2 as cv


width = 640
height = 480
bpp = 3

img = np.zeros((height, width, bpp), np.uint8)

# 왼족위,오른쪽 아래 좌표 이용
cv.rectangle(img, (50, 50),  (450, 450), (0, 0, 255), 3)
cv.rectangle(img, (150, 200), (250, 300), (0, 255, 0), -1)

# 왼쪽위 좌표가 300,150이면서 너비 높이가 각각 50 100인 내부가 마잰타색으로 채워진 사각형을 그림
cv.rectangle(img, (300, 150, 50, 100), (255, 0, 255), -1)


cv.imshow("result", img)
cv.waitKey(0)

2) 사각형의 왼쪽 위 좌표와 너비, 높이 사용  
img = cv.reactangle(img,rec,color[],thickness,lineType,shift)  
(이미지, (왼쪽위 x좌표,왼쪽위 y좌표, 너비, 높이), 색,선의 굵기, 라인타입, )



- 7-4 원 그리기  
img = cv.circle(img,center,radius, color, thickness)  
img : 이미지  
center : 중심점  
radius : 반지름  
color : 색  
thickness : 선 굵기

In [7]:
import numpy as np
import cv2 as cv


width = 640
height = 480
bpp = 3

img = np.zeros((height, width, bpp), np.uint8)


cv.circle(img, (320, 240), 10, (0, 255, 0), -1)
  
cv.circle(img, (320, 240), 100, (0, 0, 255), 1)


cv.imshow("result", img)
cv.waitKey(0);

- 7-5 선분그리기  
img = cv.line(img, pt1, pt1, color, thickness)  
img : 선분그릴 이미지  
pt1 : 시작점  
pt2 : 끝점  
color : 선분 색  
thickness : 선의 굵기

In [8]:
import numpy as np
import cv2 as cv


width = 640
height = 480
bpp = 3

img = np.zeros((height, width, bpp), np.uint8)

 
cv.line(img, (width-1, 0), (0, height-1), (0, 255, 0), 3)
cv.line(img, (0, 0), (width-1, height-1), (0, 0, 255), 3) 


cv.imshow("result", img)
cv.waitKey(0);

연습문제)  

1) 300*300 크기의 검정색  

2) (50,50) -> (150,150) 두께는 1인 빨간색 직선 그리기

3) 왼쪽위 모서리(100,100), 뚜께는 10인 오른쪽 아래 모서리가 (200,200)인 초록색 사각형 그리기

4) 중심이 (150,150), 반지름 50, 색상은 파란색, 두께는 2인 원을 그리기

In [2]:
import numpy as np
import cv2 as cv

width = 300
height = 300

# 1번 문항
img = np.zeros((height, width, 3), np.uint8)

img_h = img.shape[0]
img_w = img.shape[1]
img_bpp = img.shape[2]

# 2번 문항
cv.line(img, (50, 50), (150, 150), (255, 0, 0), 1)

# 3번 문항
cv.rectangle(img, (100, 100),  (200, 200), (0, 255, 0), 10)

# 4번 문항
cv.circle(img, (150, 150), 50, (0, 0, 255), 2)

cv.imshow("drawing", img)

cv.waitKey(0)

-1

- 7-7 폴리곤 그리기(p.159)  
1) 다각형 선 그리기  
폴리곤(polygon)을 그리는 함수인 polylines. fillpoly 함수를 제공합니다.  
cv.polylines(img, [pts], isClosed, color, thickness)  
img : 이미지  
[pts] : 다각형의 꼭지점 배열  
isClosed : 도형의 닫힘 유무 (True, False) -> True면 도형이 닫힌형태, False 열린형태  
color: 선의 색,  thickness : 선의 굵기  

2) 색칠된 다각형 그리기  
cv.fillpoly(img,[pts],color)  
img : 이미지  
[pts] : 다각형의 꼭지점 배열  
color: 선의 색,  thickness : 선의 굵기  

In [7]:
import numpy as np
import cv2 as cv


width = 640
height = 640
bpp = 3


img = np.zeros((height, width, bpp), np.uint8)


red = (0, 0, 255)
green = (0, 255, 0)
yellow = (0, 255, 255)


thickness = 2 


pts = np.array([[315, 50], [570, 240], [475, 550], 
    [150, 550], [50, 240]], np.int32)
pts = pts.reshape((-1, 1, 2))
cv.polylines(img, [pts], False, red, thickness)  



pts = np.array([[315, 160], [150, 280], [210, 480], 
    [420, 480], [480, 280]], np.int32)
pts = pts.reshape((-1, 1, 2))
cv.polylines(img, [pts], True, green, thickness)  

 
pts = np.array([[320, 245], [410, 315], [380, 415], 
    [265, 415], [240, 315]], np.int32)
pts = pts.reshape((-1, 1, 2))
cv.fillPoly(img, [pts], yellow)




cv.imshow("drawing", img)
cv.waitKey(0)

error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'fillPoly'
> Overload resolution failed:
>  - Argument 'lineType' is required to be an integer
>  - Argument 'lineType' is required to be an integer


- 7-8 글자 출력  
1) putText 함수를 제공  
cv.putTeext(img, str, location, font, fontScale, color, thickness)  
img : 글을 추가할 이미지  
str : 텍스트 문자열 입력 부분 예) 'text'
location : 표시할 좌표  
font : 폰트  
fontScale = 폰트 스케일  
color = 색 , thickness = 선두께  

In [9]:
import numpy as np
import cv2 as cv


img_w = 640
img_h = 480
bpp = 3


img = np.zeros((img_h, img_w, bpp), np.uint8)


red = (0, 0, 255)
green = (0, 255, 0)
white = (255, 255, 255)
yellow = (0, 255, 255)


center_x = int(img_w / 2.0)
center_y = int(img_h / 2.0)



thickness = 2 

location = (center_x - 200, center_y - 100)
font = cv.FONT_HERSHEY_SCRIPT_SIMPLEX  
fontScale = 3.5
cv.putText(img, 'OpenCV', location, font, fontScale, yellow, thickness)



location = (center_x - 150, center_y + 20)
font = cv.FONT_ITALIC  
fontScale = 2
cv.putText(img, 'Tutorial', location, font, fontScale, red, thickness)



location = (center_x - 250, center_y + 100)
font = cv.FONT_HERSHEY_SIMPLEX 
fontScale = 1.5
cv.putText(img, 'webnautes.tistory.com', location, font, fontScale, white, thickness)



location = (center_x - 130, center_y + 150)
font = cv.FONT_HERSHEY_COMPLEX  # normal size serif font
fontScale = 1.2
cv.putText(img, 'webnautes', location, font, fontScale, green, thickness)


cv.imshow("drawing", img)
cv.waitKey(0)

-1